# image prep
apt-get update
apt-get install -y wget gnupg apt-utils git sudo

cd ~

# install .NET Core
# please refer to official guide for your OS
# https://docs.microsoft.com/en-us/dotnet/core/install/
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-3.1

rm -rf /tmp/dotnet-installer

# configure Quokka integration server
cd ~
cp -r ~/qrs/scripts/. ~
chmod 766 ~/update ~/launch
~/update

# now you can run ~/launch